url_cars = [
    "https://www.caranddriver.com/dodge/journey/specs/2016/dodge_journey_dodge-journey_2016/377501",
    "https://www.caranddriver.com/dodge/journey/specs/2020/dodge_journey_dodge-journey_2020/412160",
    "https://www.caranddriver.com/dodge/durango/specs/2022/dodge_durango_dodge-durango_2022/421997",
    "https://www.caranddriver.com/volvo/xc90/specs/2016/volvo_xc90_volvo-xc90_2016/374025",
    "https://www.caranddriver.com/kia/telluride/specs/2022/kia_telluride_kia-telluride_2022/423060",
    "https://www.caranddriver.com/volkswagen/atlas/specs/2018/volkswagen_atlas_volkswagen-atlas_2018/393094",
    "https://www.caranddriver.com/volkswagen/atlas/specs/2018/volkswagen_atlas_volkswagen-atlas_2018/393092",
    "https://www.caranddriver.com/volkswagen/atlas/specs/2018/volkswagen_atlas_volkswagen-atlas_2018/393091",
    "https://www.caranddriver.com/subaru/ascent/specs/2019/subaru_ascent_subaru-ascent_2019/398808",
    "https://www.caranddriver.com/jeep/grand-cherokee-l/specs",
    "https://www.caranddriver.com/jeep/grand-wagoneer/specs/2022/jeep_grand-wagoneer_grand-wagoneer_2022",
    "https://www.caranddriver.com/jeep/wagoneer/specs/2022/jeep_wagoneer_jeep-wagoneer_2022",
    "https://www.caranddriver.com/honda/pilot-2021/specs/2016/honda_pilot_honda-pilot_2016/378780",
    "https://www.caranddriver.com/mazda/cx-9/specs/2022/mazda_cx-9_mazda-cx-9_2022/425098",
    "https://www.caranddriver.com/mazda/cx-9/specs/2022/mazda_cx-9_mazda-cx-9_2022/425101",
    ]

columns_ordered = [
    "Third Row Head Room (inches)",
    "Third Row Leg Room (inches)",
    "Third Row Shoulder Room (inches)",
    "Third Row Hip Room (inches)",
    "Displacement (liters/cubic inches)",
    "Maximum Horsepower @ RPM",
    "CO2 Emissions, 15K mi/year (tons)",
    "EPA Fuel Economy, combined/city/highway (mpg)",
    "Length (inches)",
    "Width, without mirrors (inches)",
    "Height (inches)",
    "Passenger / Seating Capacity",
    "Cargo Space/Area Behind Second Row (cubic feet)",
    "Cargo Space/Area Behind Third Row (cubic feet)",
    "Front Tire Size",
    "Minimum Ground Clearance (inches)",
    "Range, city/highway (miles)",
    "EPA Classification",
    "Drivetrain",
    "Engine Order Code",
    "Engine Type and Required Fuel",
    "Fuel System    Maximum Torque @ RPM",]